export const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'];
export const PERIODS=[{id:0,name:'Tutor time',start:'08:25',end:'08:40'},{id:1,name:'Lesson 1',start:'08:40',end:'09:40'},{id:2,name:'Lesson 2',start:'09:40',end:'10:40'},{id:'break',name:'Break',start:'10:40',end:'11:00'},{id:3,name:'Lesson 3',start:'11:00',end:'12:10'},{id:4,name:'Lesson 4',start:'12:10',end:'13:20'},{id:'lunch',name:'Lunch',start:'13:20',end:'14:00'},{id:5,name:'Lesson 5',start:'14:00',end:'15:00'}];
export const HOUSES=[{name:'Brunel',color:'#467fc5'},{name:'Nightingale',color:'#29a58c'},{name:'Secole',color:'#b880c6'},{name:'Turning',color:'#db9f3d'}];
export const GCSE_BLOCKS={A:['History','Geography','French','Spanish','German','Religious Studies','Citizenship'],B:['Business','Computer Science','Sociology','Psychology','Media Studies','Economics','Statistics'],C:['Film Studies','Art & Design','Photography','Drama','Music','Design & Technology','Food Preparation','Physical Education']};
export const KS4={'English Language':3,'English Literature':2,'Maths':4,'Biology':2,'Chemistry':2,'Physics':2,'PE':1,'PSHE':1,'Independent Study':2};
export const KS3={'English':5,'Maths':5,'Science':4,'History':2,'Geography':2,'French':2,'Computing':1,'Art':1,'PE':2,'PSHE':1};
export const REASONS={behaviour:[['Uniform',3],['Disruption to learning',2],['Refusal to follow instructions',3],['Truancy',5],['Late to lesson',1],['Unkind behaviour',3]],reward:[['Excellent effort',2],['Outstanding work',3],['Helping others',2],['Community contribution',5],['House competition',5]]};
export const uid=()=>crypto.randomUUID();
export const clone=v=>structuredClone(v);
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const parseDate=s=>new Date(s+'T12:00:00');
export const weekday=s=>(parseDate(s).getDay()+6)%7;
export const nice=s=>s?parseDate(s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—';
export const mins=s=>Number(s.split(':')[0])*60+Number(s.split(':')[1]);
export const timeAfter=(s,n)=>`${String(Math.floor((mins(s)+Number(n))/60)).padStart(2,'0')}:${String((mins(s)+Number(n))%60).padStart(2,'0')}`;
export function rand(n){if(n<1)throw Error('Invalid random range');const max=Math.floor(4294967296/n)*n;let x;do{x=crypto.getRandomValues(new Uint32Array(1))[0]}while(x>=max);return x%n}
export function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=rand(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
export function makeCode(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('').toUpperCase().match(/.{1,8}/g).join('-')}
export function candidate(existing){if(existing.size>=9999)throw Error('All candidate numbers are in use.');let n;do{n=String(rand(9999)+1).padStart(4,'0')}while(existing.has(n));return n}
export function csvParse(text){text=String(text).replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('CSV contains an unclosed quote.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
export function csvWrite(rows){return '\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@\-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}).join(',')).join('\r\n')}
export function parseNames(text,order='first-last'){
 const rows=csvParse(text);const names=[],errors=[];let header=null;
 if(rows[0]?.some(v=>/^(first[ _]?name|last[ _]?name|surname|forename|full[ _]?name)$/i.test(v)))header=rows.shift().map(x=>x.toLowerCase().replace(/[ _]/g,''));
 rows.forEach((r,i)=>{let first='',last='';if(header){const f=header.findIndex(v=>['firstname','forename'].includes(v)),l=header.findIndex(v=>['lastname','surname'].includes(v));if(f>=0&&l>=0){first=r[f]||'';last=r[l]||''}else r=[r[header.indexOf('fullname')]||'']}
  if(!first&&!last){let parts=r;if(r.length===1){parts=r[0].split(/\s+[–—-]\s+|\t+/);if(parts.length===1){const words=r[0].trim().split(/\s+/);parts=order==='first-last'?[words.shift(),words.join(' ')]:[words.slice(0,-1).join(' '),words.at(-1)]}}if(parts.length!==2){errors.push(`Row ${i+1}: use two name columns, or First - Last.`);return}[first,last]=order==='first-last'?parts:[parts[1],parts[0]]}
  first=(first||'').trim();last=(last||'').trim();if(!first||!last||first.length>80||last.length>100||/[<>\d]/.test(first+last)){errors.push(`Row ${i+1}: enter a valid first and last name.`);return}names.push({first,last});});return {names,errors};
}
export function schoolClosed(s,date=today()){return s.school.status!=='open'||s.closures.some(c=>date>=c.start&&date<=c.end&&c.status!=='open')}
export function closureReason(s,date=today()){return s.closures.find(c=>date>=c.start&&date<=c.end&&c.status!=='open')?.reason||s.school.reason||'The school is closed or closing.'}
export const studentsIn=(s,id)=>s.students.filter(x=>!x.archived&&(x.tutorId===id||x.classIds.includes(id)));
export function getClass(s,id){return s.classes.find(x=>x.id===id)}
export function timetable(s,student,date){const day=weekday(date);if(day>4)return [];return PERIODS.map(p=>{if(p.id===0)return {...p,subject:s.tutors.find(t=>t.id===student.tutorId)?.name||'Tutor time',room:'Tutor base'};if(typeof p.id!=='number')return {...p,subject:p.name};const c=s.classes.find(c=>student.classIds.includes(c.id)&&c.meetings.some(m=>m.day===day&&m.period===p.id));const meeting=c?.meetings.find(m=>m.day===day&&m.period===p.id);const exam=s.exams.find(e=>e.date===date&&student.classIds.includes(e.classId)&&mins(e.start)<mins(p.end)&&mins(timeAfter(e.start,e.duration))>mins(p.start));const cover=s.covers.find(v=>v.date===date&&v.classId===c?.id&&Number(v.period)===p.id);const removal=s.removals.some(r=>r.studentId===student.id&&r.date===date&&r.periods.includes(p.id));return {...p,classId:c?.id,subject:exam?exam.paper:c?.subject||'Independent study',className:c?.name,room:exam?s.rooms.find(r=>r.id===exam.roomId)?.name:s.rooms.find(r=>r.id===meeting?.roomId)?.name,teacher:s.teachers.find(t=>t.id===(cover?.teacherId||c?.teacherId))?.name,cover:!!cover,exam:!!exam,removed:removal,closed:schoolClosed(s,date)}})}
export function createClasses(s,{year=11,sets=5,mode='all',subject=''}){
 year=Number(year);sets=Number(sets);if(year<7||year>11||sets<1||sets>12)throw Error('Choose Year 7–11 and between 1 and 12 sets.');
 const spec=year>=10?KS4:KS3;const wanted=[];
 if(['all','core'].includes(mode))for(const name of Object.keys(spec))for(let set=1;set<=sets;set++)wanted.push({subject:name,set:'GM'+set,kind:'core',block:''});
 if(year>=10&&['all','gcse'].includes(mode))for(const [block,names] of Object.entries(GCSE_BLOCKS))for(const name of names)for(const set of ['History','Geography'].includes(name)?['A','B']:[''])wanted.push({subject:name,set,kind:'option',block});
 if(mode==='single'){const block=Object.keys(GCSE_BLOCKS).find(b=>GCSE_BLOCKS[b].includes(subject));if(subject in spec){for(let set=1;set<=sets;set++)wanted.push({subject,set:'GM'+set,kind:'core',block:''})}else if(block&&year>=10){for(const set of ['History','Geography'].includes(subject)?['A','B']:[''])wanted.push({subject,set,kind:'option',block})}else throw Error('Choose a subject available for this year group.')}
 let count=0;for(const item of wanted){if(s.classes.some(c=>c.year===year&&c.subject===item.subject&&c.set===item.set&&c.kind===item.kind))continue;const teacher={id:uid(),name:teacherName(s.teachers.length),department:item.subject};s.teachers.push(teacher);s.classes.push({id:uid(),year,...item,name:`${year}${item.set} ${item.subject}`,teacherId:teacher.id,capacity:32,meetings:[]});count++}
 return count;
}
const surnames=['Bennett','Clarke','Patel','Morgan','Walker','Davies','Shah','Hughes','Wilson','Reed','Taylor','Brooks','Foster','Ahmed','Cooper','Green','Phillips','Lewis','Martin','Wood','Turner','Hayes','Roberts','Price','Mills','Ali','Ward','Kelly','James','Collins','Baker','Reynolds'];
export function teacherName(i){return `${['Ms','Mr','Dr'][i%3]} ${String.fromCharCode(65+Math.floor(i/surnames.length))}. ${surnames[i%surnames.length]}`}
export function buildRooms(){const rooms=[];for(const [prefix,count,type] of [['G',24,'General'],['S',12,'Science'],['A',6,'Arts'],['T',6,'Technology'],['I',6,'Computing']])for(let i=1;i<=count;i++)rooms.push({id:uid(),code:prefix+String(i).padStart(2,'0'),name:prefix+String(i).padStart(2,'0'),building:prefix==='G'?'Learning block':type+' block',type,capacity:32,teaching:true});rooms.push(...[{code:'P01',name:'P01 · Gym',type:'PE',capacity:40,teaching:true},{code:'P02',name:'P02 · Sports Hall',type:'PE',capacity:120,teaching:true},{code:'P01-ER',name:'Equipment Room · P01',type:'Store',capacity:0,teaching:false},{code:'P02-PO',name:'PE Office · P02',type:'Office',capacity:6,teaching:false},{code:'P03',name:'Playing field',type:'PE',capacity:90,teaching:true},{code:'H01',name:'Main Hall',type:'Exams',capacity:180,teaching:true}].map(r=>({...r,id:uid(),building:'Sports & assembly'})));return rooms}
function roomType(subject){return /^(PE|Physical Education)$/.test(subject)?'PE':/Biology|Chemistry|Physics|Science/.test(subject)?'Science':/Comput/.test(subject)?'Computing':/Art|Photography|Music|Drama|Film/.test(subject)?'Arts':/Technology|Food/.test(subject)?'Technology':'General'}
export function generateTimetables(s){
 const previous=clone(s.classes);const years=[...new Set(s.classes.map(c=>c.year))].sort();
 for(let attempt=0;attempt<180;attempt++){
  s.classes.forEach(c=>c.meetings=[]);
  for(const year of years){const classes=s.classes.filter(c=>c.year===year);const optionSlots={A:[2,17],B:[7,22],C:[12,24]};const fixed=year>=10?Object.values(optionSlots).flat():[];const available=Array.from({length:25},(_,i)=>i).filter(i=>!fixed.includes(i));
   const sets=[...new Set(classes.filter(c=>c.kind==='core').map(c=>c.set))];
   for(const set of sets){const items=classes.filter(c=>c.kind==='core'&&c.set===set);const slots=shuffle(available);let pos=0;for(const c of items){const n=(year>=10?KS4:KS3)[c.subject]||1;for(let k=0;k<n&&pos<slots.length;k++){const index=slots[pos++];c.meetings.push({day:Math.floor(index/5),period:index%5+1,roomId:''})}}}
   for(const c of classes.filter(c=>c.kind==='option'))for(const index of optionSlots[c.block]||[])c.meetings.push({day:Math.floor(index/5),period:index%5+1,roomId:''});
  }
  let ok=true;for(let day=0;day<5&&ok;day++)for(let period=1;period<=5&&ok;period++){
   const items=s.classes.filter(c=>c.meetings.some(m=>m.day===day&&m.period===period));const used=new Set(),teachers=new Set();
   items.sort((a,b)=>(roomType(a.subject)==='PE'?-1:0)-(roomType(b.subject)==='PE'?-1:0));
   for(const c of items){if(teachers.has(c.teacherId)){ok=false;break}teachers.add(c.teacherId);const type=roomType(c.subject);const room=s.rooms.find(r=>r.teaching&&r.type===type&&!used.has(r.id))||(type!=='PE'?s.rooms.find(r=>r.teaching&&r.type==='General'&&!used.has(r.id)):null);if(!room){ok=false;break}used.add(room.id);c.meetings.find(m=>m.day===day&&m.period===period).roomId=room.id}
  }
  if(ok)return;
 }
 s.classes=previous;throw Error('Not enough conflict-free teaching space. Add classrooms or reduce the number of sets, then generate again.');
}
export function importStudents(s,names,year,tutorId){
 year=Number(year);const tutor=s.tutors.find(t=>t.id===tutorId&&t.year===year);if(!tutor)throw Error('Choose a tutor group belonging to the selected year.');
 const seen=new Set(s.students.filter(x=>!x.archived).map(x=>`${x.year}:${x.first} ${x.last}`.toLowerCase()));const unique=[],skipped=[];for(const n of names){const key=`${year}:${n.first} ${n.last}`.toLowerCase();if(seen.has(key)){skipped.push(n);continue}seen.add(key);unique.push(n)}
 if(studentsIn(s,tutorId).length+unique.length>tutor.capacity)throw Error(`This group has capacity for ${Math.max(0,tutor.capacity-studentsIn(s,tutorId).length)} more pupils. Increase its capacity or split the import.`);
 if(!s.classes.some(c=>c.year===year&&c.kind==='core')){createClasses(s,{year,sets:5});generateTimetables(s)}
 const existingNumbers=new Set(s.students.map(x=>x.candidateNumber)),codes=new Set(s.students.map(x=>x.loginCode));const added=[];
 for(const n of shuffle(unique)){
  const core=s.classes.filter(c=>c.year===year&&c.kind==='core'),sets=[...new Set(core.map(c=>c.set))];const set=shuffle(sets).sort((a,b)=>s.students.filter(x=>x.year===year&&x.set===a&&!x.archived).length-s.students.filter(x=>x.year===year&&x.set===b&&!x.archived).length)[0];
  const classIds=core.filter(c=>c.set===set).map(c=>c.id);if(core.filter(c=>c.set===set).some(c=>studentsIn(s,c.id).length>=c.capacity))throw Error('The year group is full. Create more sets before importing.');
  if(year>=10)for(const block of ['A','B','C']){const options=s.classes.filter(c=>c.year===year&&c.kind==='option'&&c.block===block&&studentsIn(s,c.id).length<c.capacity);if(!options.length)throw Error('Create GCSE option classes in each block A, B and C before importing.');const selected=shuffle(options).sort((a,b)=>studentsIn(s,a.id).length-studentsIn(s,b.id).length)[0];classIds.push(selected.id)}
  const house=shuffle(s.houses).sort((a,b)=>s.students.filter(x=>x.house===a.name&&!x.archived).length-s.students.filter(x=>x.house===b.name&&!x.archived).length)[0].name;
  let loginCode;do{loginCode=makeCode()}while(codes.has(loginCode));codes.add(loginCode);const candidateNumber=candidate(existingNumbers);existingNumbers.add(candidateNumber);
  const student={id:uid(),...n,year,tutorId,set,house,classIds,loginCode,candidateNumber,joined:today(),archived:false};s.students.push(student);added.push(student);
 }
 return {added,skipped};
}
export function markAttendance(s,{date,period,classId,marks}){if(schoolClosed(s,date))throw Error('Attendance is locked while school is closed or closing. Nothing has been recorded.');if(weekday(date)>4)throw Error('Registers are available on school days only.');if(![0,1,2,3,4,5].includes(Number(period)))throw Error('Choose a lesson.');const groupStudents=studentsIn(s,classId);if(Number(period)>0&&!getClass(s,classId)?.meetings.some(m=>m.day===weekday(date)&&m.period===Number(period)))throw Error('That class does not meet in this lesson.');for(const m of marks){if(!groupStudents.some(x=>x.id===m.studentId))throw Error('A pupil is not a member of this register.');if(!['present','absent','late','ill','authorised','medical','removed'].includes(m.mark))throw Error('Choose a valid attendance mark.');const removal=s.removals.some(r=>r.date===date&&r.studentId===m.studentId&&r.periods.includes(Number(period)));const row={id:`${m.studentId}:${date}:${period}`,studentId:m.studentId,date,period:Number(period),classId,mark:removal?'removed':m.mark,notes:m.notes||'',updatedAt:new Date().toISOString()};const i=s.attendance.findIndex(x=>x.id===row.id);if(i<0)s.attendance.push(row);else s.attendance[i]=row}}
export function removeFromLesson(s,studentId,date,period,reason){if(schoolClosed(s,date))throw Error('The school is closed or closing. Attendance cannot be recorded.');period=Number(period);if(![1,2,3,4,5].includes(period)||weekday(date)>4)throw Error('Choose a teaching lesson on a school day.');const student=s.students.find(x=>x.id===studentId&&!x.archived);if(!student)throw Error('Choose a current pupil.');const periods=period<4?[period,period+1]:[period];const removal={id:uid(),studentId,date,periods,reason,createdAt:new Date().toISOString()};s.removals.push(removal);for(const p of periods){const lesson=timetable(s,student,date).find(l=>l.id===p);if(lesson?.classId)markAttendance(s,{date,period:p,classId:lesson.classId,marks:[{studentId,mark:'removed',notes:reason}]})}return removal}
export function schoolDays(start,end){const out=[];for(let d=parseDate(start);d<=parseDate(end);d.setDate(d.getDate()+1)){if(out.length>400)throw Error('Choose a shorter date range.');if(d.getDay()!==0&&d.getDay()!==6)out.push(iso(d))}return out}
export function createExamCycle(s,{start,end,type,year}){year=Number(year);if(!['Mock 1','Mock 2','Mock 3','GCSE'].includes(type)||!(year===10&&type==='Mock 1'||year===11&&type!=='Mock 1'))throw Error('Mock 1 is for Year 10. Mock 2, Mock 3 and GCSE are for Year 11.');if(!start||!end||start>end)throw Error('Choose a valid exam date range.');const dates=schoolDays(start,end);if(type!=='GCSE'&&dates.length!==5)throw Error('A mock cycle must span exactly five school days.');if(dates.some(d=>schoolClosed(s,d)))throw Error('This cycle includes a closed school day. Reopen the school or change the dates.');const cycle={id:uid(),start,end,type,year};s.cycles.push(cycle);return cycle}
export function addExam(s,exam){if(schoolClosed(s,exam.date))throw Error('An exam falls on a school closure.');if(s.exams.some(e=>e.date===exam.date&&mins(e.start)<mins(timeAfter(exam.start,exam.duration))&&mins(timeAfter(e.start,e.duration))>mins(exam.start)&&s.students.some(p=>!p.archived&&p.classIds.includes(e.classId)&&p.classIds.includes(exam.classId))))throw Error('An exam clashes with another exam for the same pupils.');s.exams.push({...exam,id:uid()});const c=getClass(s,exam.classId);s.announcements.push({id:uid(),scope:'class',groupId:c.id,title:exam.paper+' · '+nice(exam.date),body:`${exam.paper}\n${nice(exam.date)}, ${exam.start}–${timeAfter(exam.start,exam.duration)}\n${s.rooms.find(r=>r.id===exam.roomId)?.name||'Exam room to be confirmed'}\n${exam.official?'Imported official GCSE timetable.':'School mock timetable.'}`,date:today(),sourceExam:true})}
export function generateMocks(s,cycleId){const cycle=s.cycles.find(c=>c.id===cycleId);if(!cycle||cycle.type==='GCSE')throw Error('Choose a mock exam cycle. Official GCSE dates must come from CSV.');if(s.exams.some(e=>e.cycleId===cycleId))throw Error('This cycle already has exams. Create a new cycle rather than duplicating sittings.');const dates=schoolDays(cycle.start,cycle.end),topics=cycle.type==='Mock 3'?['English Literature','Maths','Physics','A','C']:['English Language','Maths','Biology','A','B'];let count=0;dates.forEach((date,i)=>{for(const c of s.classes.filter(c=>c.year===cycle.year&&(c.subject===topics[i]||c.kind==='option'&&c.block===topics[i]))){addExam(s,{cycleId,classId:c.id,paper:c.subject+' · '+cycle.type,date,start:'08:40',duration:120,roomId:s.rooms.find(r=>r.type==='Exams').id,official:false});count++}});return count}
export function parseOfficialCSV(s,text,cycleId){const cycle=s.cycles.find(c=>c.id===cycleId&&c.type==='GCSE');if(!cycle)throw Error('Set GCSE dates on the calendar first, then choose that cycle.');const rows=csvParse(text),head=(rows.shift()||[]).map(v=>v.toLowerCase().replace(/\s+/g,'_'));for(const col of ['subject','paper','date','start_time','duration_minutes'])if(!head.includes(col))throw Error('Missing CSV column: '+col);const exams=[];const errors=[];rows.forEach((cells,i)=>{const row=Object.fromEntries(head.map((h,k)=>[h,cells[k]||'']));let date=row.date;const uk=date.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(uk)date=`${uk[3]}-${uk[2]}-${uk[1]}`;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||isNaN(parseDate(date))||iso(parseDate(date))!==date||date<cycle.start||date>cycle.end||weekday(date)>4){errors.push(`Row ${i+2}: date must be a school day inside the selected GCSE cycle.`);return}if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(row.start_time)||!/^\d+$/.test(row.duration_minutes)||Number(row.duration_minutes)<1||Number(row.duration_minutes)>240||mins(row.start_time)+Number(row.duration_minutes)>1080){errors.push(`Row ${i+2}: use HH:MM and a duration from 1 to 240 minutes, ending by 18:00.`);return}const aliases={'mathematics':'maths','english language':'english language','english literature':'english literature','art and design':'art & design','business studies':'business'};let subject=row.subject.toLowerCase();subject=aliases[subject]||subject;const classes=s.classes.filter(c=>c.year===cycle.year&&c.subject.toLowerCase()===subject&&(!row.class||c.name.toLowerCase()===row.class.toLowerCase()));if(!classes.length){errors.push(`Row ${i+2}: no class matches ${row.subject}${row.class?' / '+row.class:''}.`);return}if(!row.paper){errors.push(`Row ${i+2}: enter a paper name.`);return}for(const c of classes)exams.push({cycleId,classId:c.id,paper:row.paper,date,start:row.start_time,duration:Number(row.duration_minutes),roomId:s.rooms.find(r=>r.type==='Exams').id,official:true,board:row.board||''})});return {exams,errors}}
export function teacherBusy(s,teacherId,date,period,excludeClass=''){const covered=s.covers.filter(c=>c.date===date&&Number(c.period)===Number(period));if(covered.some(c=>c.teacherId===teacherId&&c.classId!==excludeClass))return true;return s.classes.some(c=>c.id!==excludeClass&&c.teacherId===teacherId&&c.meetings.some(m=>m.day===weekday(date)&&m.period===Number(period))&&!covered.some(v=>v.classId===c.id))}
export function addCover(s,data){if(weekday(data.date)>4)throw Error('Choose a school day.');const c=getClass(s,data.classId);if(!c?.meetings.some(m=>m.day===weekday(data.date)&&m.period===Number(data.period)))throw Error('The class does not meet at that time.');if(data.teacherId===c.teacherId)throw Error('Choose a different teacher to provide cover.');if(teacherBusy(s,data.teacherId,data.date,data.period,data.classId))throw Error('This teacher is already teaching or covering that lesson.');s.covers=s.covers.filter(v=>!(v.classId===data.classId&&v.date===data.date&&Number(v.period)===Number(data.period)));s.covers.push({...data,period:Number(data.period),id:uid()})}
