export const SECTIONS={timetable:'Timetable',classes:'Classes',exams:'Exams',notices:'Notices',homework:'Homework',reports:'Reports',evenings:'Parents’ evening',helpdesk:'Office helpdesk',activities:'Clubs & trips',revision:'Revision hub'};
export const escapeHTML=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const uid=()=>crypto.randomUUID();
export const safeURL=url=>{try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
export function readFile(file){if(!file)return Promise.resolve(null);if(file.size>2*1024*1024)throw Error('Choose a file of 2 MB or less.');if(!/\.(pdf|png|jpe?g|txt|docx|xlsx|pptx|csv)$/i.test(file.name))throw Error('Use a PDF, image, text, CSV or Office file.');return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(Error('Could not read this file.'));r.onload=()=>resolve({name:file.name,type:file.type||'application/octet-stream',base64:String(r.result).split(',')[1],size:file.size});r.readAsDataURL(file)})}
export function downloadFile(f){const bytes=Uint8Array.from(atob(f.base64),x=>x.charCodeAt(0));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
export function downloadCSV(name,rows){const value=rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@\-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+value],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
export function modal(title,content){let d=document.querySelector('#hubDialog');if(!d){d=document.createElement('dialog');d.id='hubDialog';d.className='wide';document.body.append(d)}d.innerHTML=`<div class="modal-head"><h2>${escapeHTML(title)}</h2><button type="button" id="hubClose" aria-label="Close">×</button></div><div class="modal-body">${content}</div>`;d.querySelector('#hubClose').onclick=()=>d.close();if(!d.open)d.showModal();return d}
export const closeModal=()=>document.querySelector('#hubDialog')?.close();
export const options=(arr,selected='')=>arr.map(([id,name])=>`<option value="${escapeHTML(id)}"${String(id)===String(selected)?' selected':''}>${escapeHTML(name)}</option>`).join('');
export function printReports(items,student,school='Westview Secondary'){let root=document.querySelector('#reportPrint');if(!root){root=document.createElement('section');root.id='reportPrint';document.body.append(root)}root.innerHTML=`<h1>${escapeHTML(school)}</h1><h2>Student report</h2><p>${escapeHTML(student.first+' '+student.last)} · Year ${escapeHTML(student.year)} · Candidate ${escapeHTML(student.candidateNumber)}</p>${items.map(i=>`<article><h3>${escapeHTML(i.data.subject)} · ${escapeHTML(i.data.term)}</h3><p><strong>Grade:</strong> ${escapeHTML(i.data.grade||'Not entered')} &nbsp; <strong>Effort:</strong> ${escapeHTML(i.data.effort||'Not entered')}</p><p style="white-space:pre-wrap">${escapeHTML(i.data.body)}</p></article>`).join('')}<footer>OneEducation school reports</footer>`;document.body.classList.add('printing-report');window.print();document.body.classList.remove('printing-report');root.remove()}
