import {portal,studentAction} from './api.mjs';
import {PERIODS,DAYS,weekday,mins,timeAfter} from './core.mjs';
import {SECTIONS,escapeHTML as esc,today,safeURL,readFile,downloadFile,modal,closeModal,options,printReports} from './hub-shared.mjs';
const app=document.getElementById('app'),by=id=>document.getElementById(id);
let data=null,view='home',code=sessionStorage.getItem('oe-student-code')||'',loading=false,generation=0;
sessionStorage.removeItem('oe-student');
const allowed=key=>data?.permissions?.[key]===true;
function toast(msg){by('toast').textContent=msg;by('toast').className='show';setTimeout(()=>by('toast').className='',4000)}
function signOut(){generation++;code='';data=null;sessionStorage.removeItem('oe-student-code');closeModal();login()}
function login(error=''){app.innerHTML=`<main class="portal-login"><section><div class="big-logo"><span></span><strong>one</strong><small>education</small></div><p class="eyebrow">STUDENT &amp; FAMILY PORTAL</p><h1>Your school day,<br>all in one place.</h1><p>Use your private student code for school information, homework and family bookings.</p></section><form id="codeForm"><h2>Open student portal</h2><label>Student login code<input id="code" autocomplete="off" spellcheck="false" required></label><button class="btn primary">Continue</button><a href="index.html">Staff sign in</a><p id="loginError" class="form-status bad" role="status">${esc(error)}</p></form></main>`;by('codeForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;code=by('code').value.trim();try{await reload();sessionStorage.setItem('oe-student-code',code)}catch(err){code='';by('loginError').textContent=err.message;e.submitter.disabled=false}}}
async function reload(silent=false){if(loading)return;loading=true;const token=++generation;try{const fresh=await portal(code);if(token!==generation)return;if(!fresh.permissions||!fresh.hub)throw Error('Your school needs to finish the portal upgrade. Please contact staff.');data=fresh;if(view!=='home'&&!allowed(view)){closeModal();view='home';}render()}catch(e){if(!silent)throw e;data=null;closeModal();login('Please sign in again to refresh your access.')}finally{loading=false}}
function lessons(date){if(!allowed('timetable')||weekday(date)>4)return[];const day=weekday(date);return PERIODS.map(p=>{if(p.id===0)return {...p,subject:data.tutors[0]?.name||'Tutor time',room:'Tutor base'};if(typeof p.id!=='number')return {...p,subject:p.name};const c=data.classes.find(c=>(c.meetings||[]).some(m=>m.day===day&&m.period===p.id)),m=c?.meetings.find(m=>m.day===day&&m.period===p.id),exam=data.exams.find(e=>e.date===date&&mins(e.start)<mins(p.end)&&mins(timeAfter(e.start,e.duration))>mins(p.start)),cover=data.covers.find(v=>v.date===date&&v.classId===c?.id&&Number(v.period)===p.id),removed=data.removals.some(r=>r.date===date&&r.periods.includes(p.id));return {...p,subject:exam?exam.paper:c?.subject||'Independent study',className:c?.name,room:data.rooms.find(r=>r.id===(exam?.roomId||m?.roomId))?.name,teacher:data.teachers.find(t=>t.id===(cover?.teacherId||c?.teacherId))?.name,exam:!!exam,removed}})}
function lesson(l){return `<div class="lesson ${l.removed?'removed':''}"><time>${l.start}</time><div><strong>${l.removed?'Scheduled to be out of lesson':esc(l.subject)}</strong><small>${esc(l.removed?'Follow staff instructions.':[l.className,l.room,l.teacher].filter(Boolean).join(' · '))}</small></div>${l.exam?'<span class="tag">Exam</span>':''}</div>`}
function weekDate(day){const d=new Date(today()+'T12:00:00');d.setDate(d.getDate()-weekday(today())+day);return d.toISOString().slice(0,10)}
const heading=(title,copy='')=>`<div class="page-head"><div><p>ONEEDUCATION</p><h1>${esc(title)}</h1>${copy?`<span>${esc(copy)}</span>`:''}</div></div>`;
function notices(){return data.announcements.slice().reverse().map(n=>`<article class="feed-item"><small>${esc(n.date)}</small><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p></article>`).join('')||'<p>No notices yet.</p>'}

function timetableGrid(){const days=DAYS.map((_,i)=>lessons(weekDate(i)));return heading('Your school week')+'<p class="hub-note">Tutor time starts at 08:25. This is your saved weekly timetable. Week B in the separate add-on remains a preview.</p><article class="card"><div class="table-scroll"><table class="hub-week"><thead><tr><th>Period</th>'+DAYS.map(d=>'<th>'+esc(d)+'</th>').join('')+'</tr></thead><tbody>'+PERIODS.filter(p=>typeof p.id==='number'&&p.id>0).map(p=>'<tr><th>P'+p.id+'<small>'+p.start+'–'+p.end+'</small></th>'+days.map(rows=>{const l=rows.find(l=>l.id===p.id);return '<td><strong>'+esc(l?.removed?'Scheduled to be out of lesson':l?.subject||'Independent study')+'</strong><small>'+esc(l?.removed?'Follow staff instructions.':[l?.className,l?.room].filter(Boolean).join(' · '))+'</small><small>'+esc(l?.teacher||'')+'</small></td>'}).join('')+'</tr>').join('')+'</tbody></table></div></article>'}

function basePage(){if(view==='home')return `${heading('Hello, '+data.student.first,'Your school chooses which sections appear here.')}<div class="portal-grid">${allowed('timetable')?`<article class="card"><p class="eyebrow">TODAY · ${esc(today())}</p><h2>Your lessons</h2>${lessons(today()).map(lesson).join('')||'<p>No teaching lessons today.</p>'}</article>`:''}<article class="card"><h2>Available sections</h2><div class="hub-list">${Object.entries(SECTIONS).filter(([k])=>allowed(k)).map(([k,t])=>`<button class="btn soft" data-view="${k}">${esc(t)}</button>`).join('')||'<p>Your school has hidden all sections for now. Contact your tutor if you need help.</p>'}</div></article>${allowed('notices')?`<article class="card"><h2>Latest notices</h2>${notices()}</article>`:''}</div>`;
if(view==='timetable')return timetableGrid();
if(view==='classes')return `${heading('Your teaching groups')}<div class="tile-grid">${data.classes.map(c=>`<article class="community"><div class="community-art"><span>${esc(c.subject.slice(0,2))}</span><small>YEAR ${c.year}</small></div><div><h2>${esc(c.name)}</h2><p>${esc(data.teachers.find(t=>t.id===c.teacherId)?.name||'')}</p></div></article>`).join('')}</div>`;
if(view==='exams')return `${heading('Your exam timetable')}<article class="card">${data.exams.slice().sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).map(e=>`<div class="exam-row"><time>${esc(e.date)}<small>${esc(e.start)} · ${esc(e.duration)} minutes</small></time><div><strong>${esc(e.paper)}</strong><small>${esc(data.rooms.find(r=>r.id===e.roomId)?.name||'Room to be confirmed')}</small></div><span class="tag">${e.official?'GCSE':'School mock'}</span></div>`).join('')||'<p>No exams published yet.</p>'}</article>`;
if(view==='notices')return `${heading('School and community notices')}<article class="card community-feed">${notices()}</article>`;return hubPage()}
const myAction=(i,k)=>data.hub.actions.find(a=>a.item_id===i.id&&a.kind===k);
function links(i){return `<div class="hub-actions">${i.data.attachment?`<button class="btn soft" data-download="${i.id}">Download ${esc(i.data.attachment.name)}</button>`:''}${safeURL(i.data.url)?`<a class="btn soft" href="${esc(safeURL(i.data.url))}" target="_blank" rel="noopener noreferrer">Open resource</a>`:''}</div>`}
function hubPage(){if(view==='helpdesk')return `${heading('School office helpdesk','For routine enquiries. Tell a member of staff directly about urgent problems.')}<button class="btn primary" id="portalTicket">New request</button><div class="hub-list">${data.hub.actions.filter(a=>a.kind==='ticket').map(a=>`<article class="card hub-item"><div class="hub-title-line"><h2>${esc(a.data.title)}</h2><span class="hub-pill">${esc(a.data.status)}</span></div><small>${esc(a.data.category)} · ${esc(a.data.location)}</small><p>${esc(a.data.body)}</p>${a.data.feedback?`<p><strong>Office reply:</strong> ${esc(a.data.feedback)}</p>`:'<small>Waiting for a reply.</small>'}</article>`).join('')}</div>`;
const kind={homework:'homework',reports:'report',evenings:'evening',activities:'activity',revision:'revision'}[view],items=data.hub.items.filter(i=>i.kind===kind);return `${heading(SECTIONS[view])}${view==='reports'&&items.length?'<button class="btn soft hub-print-btn" id="printReport">Print reports / save PDF</button>':''}${view==='evenings'?'<p class="hub-note">Parents and guardians use the child’s code. Choose a free appointment with one of your teachers.</p>':''}${view==='activities'?'<p class="hub-note">Sign-ups reserve a place for staff review. Staff confirm approval and check parent/guardian consent declarations.</p>':''}<div class="hub-grid">${items.map(i=>{const d=i.data,a=myAction(i,{homework:'submission',evening:'booking',activity:'enrolment',revision:'plan'}[kind]);return `<article class="card hub-item"><div class="hub-title-line"><h2>${esc(d.title)}</h2>${a?`<span class="hub-pill">${esc(a.data.status)}</span>`:''}</div><div class="hub-meta">${kind==='evening'?`<span>${esc(data.teachers.find(t=>t.id===d.teacherId)?.name||'Teacher')}</span>`:''}${d.due?`<span>Due ${esc(d.due)}</span>`:''}${d.date?`<span>${esc(d.date)} ${esc(d.start||'')}${d.end?'–'+esc(d.end):''}</span>`:''}${d.location?`<span>${esc(d.location)}</span>`:''}${kind==='report'?`<span>${esc(d.subject)} · ${esc(d.term)}</span>`:''}${d.topic?`<span>${esc(d.topic)}</span>`:''}</div><p>${esc(d.body)}</p>${links(i)}${kind==='report'?`<p><strong>Grade:</strong> ${esc(d.grade||'Not entered')}<br><strong>Effort:</strong> ${esc(d.effort||'Not entered')}</p>`:''}${a?.data.feedback?`<p><strong>Feedback:</strong> ${esc(a.data.feedback)}${a.data.grade?'<br>Grade: '+esc(a.data.grade):''}</p>`:''}${kind==='homework'?`${a?`<small>Submitted ${esc(a.data.submittedAt?.slice(0,10))}${a.data.late?' · After the due date':''}</small>`:''}<button class="btn primary" data-submit="${i.id}">${a?'View / replace submission':'Submit homework'}</button>`:''}${kind==='evening'?`<small>${i.available} slot available</small><button class="btn ${a?.data.status==='booked'?'soft':'primary'}" data-book="${i.id}" ${!i.available&&a?.data.status!=='booked'?'disabled':''}>${a?.data.status==='booked'?'Cancel booking':'Book appointment'}</button>`:''}${kind==='activity'?`<small>${i.available} places available</small><button class="btn ${a&&a.data.status!=='cancelled'?'soft':'primary'}" data-join="${i.id}" ${!i.available&&(!a||a.data.status==='cancelled')?'disabled':''}>${a&&a.data.status!=='cancelled'?'View / cancel sign-up':'Sign up'}</button>`:''}${kind==='revision'?`${a?`<p>Planned: ${esc(a.data.targetDate)}<br>${esc(a.data.body)}</p>`:''}<button class="btn soft" data-plan="${i.id}">${a?'Update revision plan':'Plan revision'}</button>`:''}</article>`}).join('')||'<article class="card empty">Nothing published for you yet.</article>'}</div>`}
function render(){if(!data)return login();const p=data.student,closed=data.school.status!=='open'||data.closures.some(c=>today()>=c.start&&today()<=c.end&&c.status!=='open');app.innerHTML=`<div class="portal-shell"><header><a class="logo" href="#"><span></span><strong>one</strong><small>education</small></a><div><strong>${esc(p.first)} ${esc(p.last)}</strong><small>Year ${p.year} · Candidate ${esc(p.candidateNumber)}</small><button id="portalRefresh">Refresh</button><button id="portalOut">Sign out</button></div></header><nav><button data-view="home" class="${view==='home'?'active':''}">Home</button>${Object.entries(SECTIONS).filter(([k])=>allowed(k)).map(([k,t])=>`<button data-view="${k}" class="${view===k?'active':''}">${esc(t)}</button>`).join('')}</nav><main>${closed?'<div class="portal-banner">School is closed or closing. Follow the school’s latest instructions.</div>':''}${basePage()}</main><footer>OneEducation · Student &amp; family portal</footer></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});by('portalOut').onclick=signOut;by('portalRefresh').onclick=()=>reload().catch(e=>toast(e.message));by('portalTicket')?.addEventListener('click',ticket);by('printReport')?.addEventListener('click',()=>printReports(data.hub.items.filter(i=>i.kind==='report'),p));document.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>downloadFile(data.hub.items.find(i=>i.id===b.dataset.download).data.attachment));for(const [attr,fn] of [['submit',submission],['book',booking],['join',enrolment],['plan',plan]])document.querySelectorAll(`[data-${attr}]`).forEach(b=>b.onclick=()=>fn(data.hub.items.find(i=>i.id===b.dataset[attr])))}
function bindForm(d,kind,item,collect){d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await studentAction(code,kind,await collect(e.currentTarget),item?.id||null);closeModal();await reload();toast('Saved.')}catch(err){d.querySelector('[role="status"]').textContent=err.message;b.disabled=false}}}
function submission(i){const a=myAction(i,'submission');const d=modal(i.data.title,`<form class="hub-form"><label>Your answer<textarea name="body" maxlength="20000">${esc(a?.data.body||'')}</textarea></label><label>Attachment (up to 2 MB)<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.docx,.xlsx,.pptx,.csv"></label>${a?.data.attachment?`<p>Current file: ${esc(a.data.attachment.name)}</p><label class="check"><input name="remove" type="checkbox">Remove current attachment</label>`:''}<p class="hint">Resubmitting replaces your previous answer and sends it for review again.</p><p role="status" class="hub-error"></p><button class="btn primary">${a?'Replace submission':'Submit homework'}</button></form>`);bindForm(d,'submission',i,async f=>({body:f.elements.body.value,attachment:f.elements.file.files[0]?await readFile(f.elements.file.files[0]):f.elements.remove?.checked?null:a?.data.attachment||null}))}
function booking(i){const a=myAction(i,'booking'),cancel=a?.data.status==='booked';const d=modal(cancel?'Cancel appointment':i.data.title,`<form class="hub-form"><p>${esc(i.data.date)} ${esc(i.data.start)}–${esc(i.data.end)} · ${esc(i.data.location)}</p>${cancel?'<p>This releases the slot for another family.</p>':'<label>Attending parent / guardian<input name="parentName" required maxlength="160"></label>'}<p role="status" class="hub-error"></p><button class="btn primary">${cancel?'Confirm cancellation':'Confirm booking'}</button></form>`);bindForm(d,'booking',i,f=>({status:cancel?'cancelled':'booked',parentName:f.elements.parentName?.value||a?.data.parentName}))}
function enrolment(i){const a=myAction(i,'enrolment'),cancel=a&&a.data.status!=='cancelled';const d=modal(i.data.title,`<form class="hub-form"><p>${esc(i.data.date)} · ${esc(i.data.location)}</p>${cancel?`<p>Your place is ${esc(a.data.status)}. You can cancel below.</p>`:`<label>Parent / guardian name<input name="parentName" ${i.data.requiresConsent?'required':''} maxlength="160"></label>${i.data.requiresConsent?'<label class="check"><input name="consent" type="checkbox" required>I am the parent/guardian and give permission for this activity.</label>':'<p>No consent declaration is required for this activity.</p>'}`}<p role="status" class="hub-error"></p><button class="btn primary">${cancel?'Cancel sign-up':'Request a place'}</button></form>`);bindForm(d,'enrolment',i,f=>({status:cancel?'cancelled':'pending',parentName:f.elements.parentName?.value||a?.data.parentName,consent:f.elements.consent?.checked||a?.data.consent||false}))}
function plan(i){const a=myAction(i,'plan');const d=modal('Revision plan · '+i.data.title,`<form class="hub-form"><label>Revision date<input name="targetDate" type="date" required value="${esc(a?.data.targetDate||today())}"></label><label>My checklist / plan<textarea name="body" placeholder="One task per line">${esc(a?.data.body||'')}</textarea></label><label class="check"><input name="complete" type="checkbox" ${a?.data.status==='complete'?'checked':''}>Completed this revision session</label><p role="status" class="hub-error"></p><button class="btn primary">Save revision plan</button></form>`);bindForm(d,'plan',i,f=>({targetDate:f.elements.targetDate.value,body:f.elements.body.value,status:f.elements.complete.checked?'complete':'planned'}))}
function ticket(){const d=modal('New office request',`<form class="hub-form"><label>Title<input name="title" maxlength="160" required></label><label>Category<select name="category">${options(['IT','Lost property','Room request','General'].map(x=>[x,x]))}</select></label><label>Location / room<input name="location"></label><label>Message<textarea name="body" required></textarea></label><p role="status" class="hub-error"></p><button class="btn primary">Send to school office</button></form>`);bindForm(d,'ticket',null,f=>Object.fromEntries(new FormData(f)))}
if(code){app.innerHTML='<main class="portal-empty">Refreshing your portal…</main>';reload().catch(e=>{code='';sessionStorage.removeItem('oe-student-code');login(e.message)})}else login();
setInterval(()=>{if(code&&data&&!document.hidden)reload(true)},60000);

