import * as api from './api.mjs';
import {initialState} from './seed.mjs';
import {PERIODS,DAYS} from './core.mjs';
const app=document.querySelector('#app'),status=document.querySelector('#status');
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,pupils=[],demo=false;
function error(e){status.textContent=e.message||String(e)}
function accept(d,studentOnly=false){if(!d)throw Error('Open the main MIS and initialise your school first.');data=d;pupils=studentOnly?[d.student]:d.students.filter(p=>!p.archived);if(!pupils.length)throw Error('No current students are available.');render()}
function login(){app.innerHTML=`<section class="card auth"><h2>Open timetables</h2><p>Staff can choose any current student. Students and families use their private code to see their own timetable.</p><form id="staff"><label>Staff email<input id="email" type="email" autocomplete="username" required></label><label>Password<input id="password" type="password" autocomplete="current-password" required></label><button>Staff sign in</button></form><form id="student"><label>Student login code<input id="code" autocomplete="off" required></label><button>Student / family sign in</button></form><button id="demo" class="secondary">Preview with fictional students</button><p><a href="index.html">Back to the MIS</a></p></section>`;
document.querySelector('#staff').onsubmit=async e=>{e.preventDefault();await busy(e.submitter,async()=>accept((await api.signIn(document.querySelector('#email').value,document.querySelector('#password').value)).data))};
document.querySelector('#student').onsubmit=async e=>{e.preventDefault();await busy(e.submitter,async()=>accept(await api.portal(document.querySelector('#code').value),true))};
document.querySelector('#demo').onclick=()=>{demo=true;accept(initialState())}}
async function busy(b,fn){b.disabled=true;status.textContent='';try{await fn()}catch(e){error(e)}finally{b.disabled=false}}
function render(){status.textContent='';app.innerHTML=`<p class="notice">Week A shows the saved weekly lessons. Week B is a proposed rotation of those lessons, with each whole school day moved together to preserve the existing room and teacher allocations. It is a preview only: your existing registers, cover and student portal still use the original weekly timetable.</p><div class="controls"><label>Student<select id="pupil">${pupils.map(p=>`<option value="${esc(p.id)}">${esc(p.first+' '+p.last)} · ${esc(data.tutors.find(t=>t.id===p.tutorId)?.name||'Year '+p.year)}</option>`).join('')}</select></label><label>Week<select id="week"><option value="A">Week A · saved timetable</option><option value="B">Week B · proposed preview</option></select></label><button id="load">Load timetable</button><button class="secondary" id="print">Print</button><button class="secondary" id="out">${demo?'Exit demo':'Sign out'}</button></div><section class="card" id="grid"></section><div class="links"><a href="index.html">Staff MIS</a><a href="student.html">Student portal</a></div>`;document.querySelector('#load').onclick=grid;document.querySelector('#print').onclick=()=>window.print();document.querySelector('#out').onclick=()=>{if(!demo)api.signOut();data=null;pupils=[];demo=false;login()};grid()}
function grid(){const p=pupils.find(p=>p.id===document.querySelector('#pupil').value),week=document.querySelector('#week').value;const classes=data.classes.filter(c=>p.classIds.includes(c.id));const teaching=PERIODS.filter(p=>typeof p.id==='number'&&p.id>0);document.querySelector('#grid').innerHTML=`<div class="caption"><h2>${esc(p.first+' '+p.last)} · Week ${week}</h2><span>${demo?'Fictional demo · ':''}${week==='B'?'Proposed rotation · not live':'Saved weekly timetable'} · Tutor time 08:25</span></div><table aria-label="Week ${week} timetable"><thead><tr><th scope="col">Period</th>${DAYS.map(d=>`<th scope="col">${esc(d)}</th>`).join('')}</tr></thead><tbody>${teaching.map(period=>`<tr><th scope="row">P${period.id}<small>${period.start}–${period.end}</small></th>${DAYS.map((_,day)=>{const sourceDay=week==='A'?day:(day+2)%5,c=classes.find(c=>c.meetings.some(m=>m.day===sourceDay&&m.period===period.id)),m=c?.meetings.find(m=>m.day===sourceDay&&m.period===period.id);return `<td>${c?`<strong>${esc(c.subject)}</strong><small>${esc(data.rooms.find(r=>r.id===m.roomId)?.name||'Room TBC')} · ${esc(c.name)}</small><small>${esc(data.teachers.find(t=>t.id===c.teacherId)?.name||'Teacher TBC')}</small>`:'<strong class="study">Personal Development / Study</strong>'}</td>`}).join('')}</tr>`).join('')}</tbody></table>`}
login();
if(api.identity()){try{accept((await api.rpc('oe_get_state')).data)}catch(e){error(e)}}
